### ISSUE TITLE
Move Kyma Environment Broker from control-plane into new repository

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#1]
**Description**

After a discussion with SRE, we do not need a monolith repository for the control plane anymore.

**Reason**

1) We don't want to be affected by other components' tests and configurations when developing KEB.
2) Ownership for the whole repository assigned only to Gophers. We'd like to make use of GitHub actions for testing pipelines etc.
3) We can finally implement Auto-bump for PR, existing [ticket](https://github.com/orgs/kyma-project/projects/38/views/1?pane=issue&itemId=8400485) 

**Ideas**
- new repo in kyma-project org for KEB
- new way of deploying KEB into environments (find a way how we will manage charts and image versions) See how Lifecycle Manager component is used in the Argo CD.
- move tests from fast-integration to the new KEB repository.

**AC**
- [x] 1) Figure out how argoCD manages KEB in the environments. Document results in the comment. @ralikio 
- [x] 2) Check if we can easily move KEB code and deployments out of control-plane repository. Document results in the comment. 
  - [x] 2.1) Check KCP CLI if it will still work 
- [x] 3) Add all templates to this repository, labels etc (reference repository: btp-manager) Done by @MarekMichali 
- [x] 4) Make sure all git history is cloned/copied into new repository @piotrmiskiewicz @ukff 
- [x] 5) Document a process how we will switch in ARGO CD from control-plane deployments to kyma-environment-broker deployments
- [x] 6) POC: we have a KEB instance in the DEV Env deployed from the new repo. Still, KEB deployment from the control-plane is a default one.
- [x] 7) check if subscription cleanup job should be outside of KEB

**Comment by piotrmiskiewicz** [comment]
# Moving git history
1. clone the old repository:
```
git clone https://github.com/kyma-project/control-plane
cd control-plane

git remote rm origin
```
2. Remove all unnecessary files
```
git filter-branch --subdirectory-filter components/kyma-environment-broker -- --all
```
or just remove files manually and commit it (the history will contain all history from control-plane like Provisioner)
3. Checkout the existing new repository
4. Define a remote with a link the the old one:
```
git remote add old <filesystem path to the cloned old repo>
```
5. Pull from old repo:
```
git pull old main --allow-unrelated-histories --rebase
```

NOTE: if the old repo contains the same file like in the new one be aware of conflicts. Think about running:
```
rm CODE_OF_CONDUCT.md CONTRIBUTING.md LICENSE NOTICE.md README.md .gitignore
```
in the old or in the new one.

**Comment by PK85** [comment]
We made a decision to first move code and start developing KEB in the new repository, but keep deployments via control-plane. Then as a next step we will take care about moving deployment into new repository.

**Comment by MarekMichali** [comment]
These are components that have KEB dependencies
- `components/kyma-metrics-collector`
- `tests/e2e/provisioning`
- `tools/cli`

In order to move the code we could take these steps

1. Copy the code to the new repo
2. Check whether the above mentioned components will still work after changing the dependencies to the new repo
3. Check with pjtester if the KEB prow jobs will work after changing to the new repo
4. Change the dependencies in the mentioned components
5. Change KEB related prow jobs to point to the new repo
6. Remove KEB from control-plane and leave a note where to find the code base.

`pre-main-kcp-cli `and `post-main-kcp-cli` are triggered with this regex: `run_if_changed: '^tools/cli|^components'`
We need to check if we need to run the job also from the new KEB repository

**Comment by ralikio** [comment]
PR with jobs building new repository: https://github.com/kyma-project/test-infra/pull/8843

**Comment by ralikio** [comment]
Verified builds:
- [ ] "pull-new-keb-build"
- [ ] "post-new-keb-build"
- [ ] "pull-new-keb-cleanup-job-build"
- [ ] "post-new-keb-cleanup-job-build"
- [ ] "pull-new-keb-subaccount-cleanup-job-build"
- [ ] "post-new-keb-subaccount-cleanup-job-build"
- [ ] "pull-new-keb-trial-cleanup-job-build"
- [ ] "post-new-keb-trial-cleanup-job-build"
- [ ] "pull-new-keb-deprovision-retrigger-job-build"
- [ ] "post-new-keb-deprovision-retrigger-job-build"
- [ ] "pull-new-keb-runtime-reconciler-job-build"
- [ ] "post-new-keb-runtime-reconciler-job-build"

**Comment by ralikio** [comment]
## Consolidated Plan

These are components that have KEB dependencies:
- `components/kyma-metrics-collector`
- `tests/e2e/provisioning`
- `tools/cli`

In order to move the code we could take these steps:

- [ ] Clean pull requests in control plane

- [ ] Investigate if prow jobs with `run_if_changed` set to KEB are save to either remove. The reason is that we are not aware of Prow being able to trigger build across multiple repositories. For example,`pre-main-kcp-cli ` and `post-main-kcp-cli` are triggered with this regex: `run_if_changed: '^tools/cli|^components'`We need to check if we need to run the jobs also from the new KEB repository .

- [ ] Copy the code to the new repo with the history of all commits. Script that automates the process for the specified subdirectory.
    - [ ] KEB moved to https://github.com/kyma-project/kyma-environment-broker
    - [x] Copy https://github.com/kyma-project/control-plane/tree/main/components/kyma-environment-broker flattening the structure
    - [x] Copy https://github.com/kyma-project/control-plane/tree/main/resources/kcp/charts/kyma-environment-broker **leaving structure as is** 
    - [ ] Copy docs
    - [x] scripts/generic_make_go.mk (can be manually)
    - [ ] Should cleanup subscription from Frogs still be moved?


- [ ] Copy KEB related prow jobs to definitions that point to the new repo. Buliding two images. Change Prow pipelines to point to the new KEB repository
    - [ ] Check with pjtester if the KEB prow jobs will work after changing to the new repo.
    - [ ] Check whether the above mentioned components will still work (build) after changing the dependencies to the new repo.
    - [ ] Check if all `run_if_changed` are necessary

    Prow Jobs:
    - [x] "pull-new-keb-build"
    - [ ] "post-new-keb-build"
    - [x] "pull-new-keb-cleanup-job-build"
    - [ ] "post-new-keb-cleanup-job-build"
    - [x] "pull-new-keb-subaccount-cleanup-job-build"
    - [ ] "post-new-keb-subaccount-cleanup-job-build"
    - [x] "pull-new-keb-trial-cleanup-job-build"
    - [ ] "post-new-keb-trial-cleanup-job-build"
    - [x] "pull-new-keb-deprovision-retrigger-job-build"
    - [ ] "post-new-keb-deprovision-retrigger-job-build"
    - [x] "pull-new-keb-runtime-reconciler-job-build"
    - [ ] "post-new-keb-runtime-reconciler-job-build"

- [ ] Create parallel argo setup for new repository - can work on old repo, if we would like to postpone switching.
    - [ ] Customize Deployment Scripts that deploy a separate resources (separate namespace).
    - [ ] Make sure that istio that resides in the Control Plane repository does not break the build
    - [ ] Check schema-migrator


- [ ] Change the packages and dependencies in KEB and Control Plane
    - [ ] Remove KEB and rename imports in control plane - wip - https://github.com/kyma-project/control-plane/pull/3045 
    - [ ] Rename imports in new KEB repo - wip - https://github.com/kyma-project/kyma-environment-broker/pull/29
    - [ ] check if broker builds work on prow 


- [ ] Remove KEB from control-plane and leave a note where to find the code base.
    - [ ] Subchart Removal - make sure that removal of chart does not cause any downtime because it will for sure cause deployment removal.


- [ ] Github Actions
- [ ] Protect branches
- [ ] Remove repo syncing action
- [ ] Cleanup remains
- [ ] Versioning
- [ ] Does KCP Cli work?

- [ ] Run linting always ?? is it necessary?? scripts always https://github.com/ralikio/kyma-environment-broker/pull/1
- [ ] Dependa bot
- [ ] generic jobs in test-infra

**Comment by ralikio** [comment]
Missing build: https://github.com/kyma-project/test-infra/pull/8880
Dependabot: https://github.com/kyma-project/kyma-environment-broker/pull/34
ESlint: https://github.com/kyma-project/kyma-environment-broker/pull/32

**Comment by ralikio** [comment]
Version Update Bump pointing to the new repository: https://github.com/kyma-project/control-plane/pull/3068

**Comment by ralikio** [comment]
Environments Cleanup job: https://github.com/kyma-project/kyma-environment-broker/pull/46

**Comment by ralikio** [comment]
New KEB Helm chart for easy refactoring: https://github.com/kyma-project/kyma-environment-broker/pull/63
