### ISSUE TITLE
SB: Service Binding for Kyma Service Instance - Epic

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma-environment-broker#284]
**Description**
Provide a service binding for Kyma Runtime instance. The binding should contain all the information to connect to the runtime (KUBECONFIG or all the information required to build a KUBECONFIG). The binding request can create [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) and return the token in the binding. 

**Reasons**
Users can create Kyma Runtime instances with API or BTP CLI. But the instance cannot be accessed without user being authenticated (OIDC flow). Therefore any automation flow that involves provisioning Kyma and deploying any workload there cannot be easily implemented. The only way to do that is to use custom OIDC provider, but that option is not easy to set up and use.

**Attachments**
Other way to achieve the automation would be https://github.com/kyma-project/kyma/issues/18305

**AC** Added by PK
- 1) POC -  ✅ done[link](https://github.com/kyma-project/kyma-environment-broker/issues/318)
- 2) Implementation on CIS side -  🏗 in progress 
- 3) Implementation on Kyma side -  🏗 in progress 
  - [x] 3.1) Check with CIS what our endpoints must support (not all OSB API bindings options will be send from CIS to us) @PK85 
  - [ ] 3.2) https://github.com/kyma-project/kyma-environment-broker/issues/1203
  - [x] 3.3) https://github.com/kyma-project/kyma-environment-broker/issues/1197
  - [x] 3.4) https://github.com/kyma-project/kyma-environment-broker/issues/1198
  - [x] 3.5) https://github.com/kyma-project/kyma-environment-broker/issues/1199
  - [x] 3.6) https://github.com/kyma-project/kyma-environment-broker/issues/1202
  - [x] 3.7)  https://github.com/kyma-project/kyma-environment-broker/issues/1196
  - [x] 3.8)  https://github.com/kyma-project/kyma-environment-broker/issues/1204
  - [x] 3.9) https://github.com/kyma-project/kyma-environment-broker/issues/1200
  - [x] 3.10) Decide which plan is bindable (Check with PO)
  - [x] 3.11) https://github.com/kyma-project/kyma-environment-broker/issues/1205
- 4.0) Prepare release:
  - 4.1) RN (Iwona + PK)
  - 4.2) Help portal docs (Iwona + PK)
  - 4.3) deploy stage
  - 4.4) deploy prod

**Links**
1) how to make given plan bindable on given env: https://github.tools.sap/kyma/management-plane-config/blob/main/argoenv/keb/dev/values.yaml#L101, and code: https://github.com/kyma-project/kyma-environment-broker/blob/main/internal/broker/bind_create.go#L18
2) Gardener: https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md#shootsadminkubeconfig-subresource

**Comment by kwiatekus** [comment]
the static bootstrap token created at the provisioning is extremely short living. (~5min)

**Comment by PK85** [comment]
POCs:
1) create a technical user in BTP and with BTP CLI create Kyma instance and Kyma binding
2) create a technical user in BTP and create btpOperator instance and then with clientCredential create Kyma instance and Kyma binding

**Comment by danail-branekov** [comment]
FWIW, in order to address https://github.com/kyma-project/kyma/issues/18092 in our project we have come up with a [script](https://github.tools.sap/unified-runtime/trinity/blob/wip-local-uaa/scripts/tools/generate-kyma-kubeconfig.sh) that
* Uses the kyma human user kubeconfig to create an admin service account
* Generates a kubeconfig containing the service account secret

The human user has to be a cluster admin in order to be able to create the service account though.

**Comment by szwedm** [comment]
Next steps should be discussed with @pbochynski @PK85 @piotrmiskiewicz.

**Comment by kwiatekus** [comment]
@PK85, @tobiscr wouldnt' this gardener's feature offer an alternative, shortcut solution?
https://github.com/gardener/gardener/blob/master/docs/usage/shoot_access.md#shootsadminkubeconfig-subresource

**Comment by PK85** [comment]
Another meeting with CIS team needed

**Comment by PK85** [comment]
MVP proposal sent to CIS team, awaiting timelines

**Comment by PK85** [comment]
MVP proposal, awaiting for CIS team: https://wiki.one.int.sap/wiki/display/kyma/Kyma+Environment+Service+Binding+-+MVP+proposal

**Comment by PK85** [comment]
Descisions after a meeting with CIS team:

- binding ID - will be generated by ERS and the user will not have to send it to the create binding API
- context - will be filled with the user id and origin (same as in create instance)
- parameters - user will provide that as part for the ERS payload and no schema validation will be done on the parameters
- bindable - ERS will validate the service and plan bindable property, if it is false, the binding request will be rejected.
- rotate - will not be supported, the user will have to delete and create a new binding.
- service and plan IDs - will be calculated by ERS (fetched form the service instance), the user will not have to send it as part of the payload.

**Comment by PK85** [comment]
Communication from CIS (11.08.2024):

A few updates from ERS side:
1) I saw that the user is sent as part of the headers in Service Instance creation, so we will align to it
ERS is acting as a proxy - meaning - we will not save anything on our side (from bindings perspective). this leads to the following: 
  - a. The API user (call to ERS->createBinding) will need to pass the binding UUID (he is the one that manages the binding, and needs to know the ID)
  - b. We will support async creation, but polling will be on the API user's side (since we cannot poll on our side) - the user that creates the binding (and knows the ID), will request polling on that binding, from us
  - c. We will expose also API for polling last operation from the service broker

So, in terms of payload for service broker from ERS:
- binding ID - will be sent by the user, we will not generate since we can't save it on our side
- context - no need to send it, we will fill the user id and origin (same as in create instance) as part of the headers
parameters - user will provide that as part of the ERS payload and no schema validation will be done on the parameters (see bellow)
- bindable - ERS will validate the service and plan bindable property, if it is false, the binding request will be rejected.
- rotate - will not be supported, the user will have to delete and create a new binding.
- service and plan IDs - will be calculated by ERS (fetched form the service instance), the user will not have to send it as part of the payload.
- Headers - we will add user origin and email, as an encoded string in "X-Broker-API-Originating-Identity" header (same as in service instance creation)

And my answer:
1) about user id we are getting that as a part of the context for SI operations:
```
    "context": {
        ...
        "user_id": "piotr.kopczynski@sap.com"
    }
```
2) About UUID, when user creates Service Instance, the ID is generated by ERS. I think it should be still generated for user. There is as well a way to list all Environments list,

**Comment by PK85** [comment]
Areas:
- kcp CLI and REST API for runtime/bindings
- create kubeconfig
- broker API compatibility provisioning API/OSB API requirements
- we need implement DB table and functionlity aroud service bindings

**Comment by gowrisankar22** [comment]
@pbochynski Is it a right approach, for the runtime implement a service binding to provide the kubeconfig ? Usually, service binding is for the services.

**Comment by PK85** [comment]
@gowrisankar22 Service Bindings APIs are right now under implementation for Provisioning Service by CIS team. Cheers

**Comment by pbochynski** [comment]
> @pbochynski Is it a right approach, for the runtime implement a service binding to provide the kubeconfig ? Usually, service binding is for the services.

Exactly - Kyma runtime is a service and this is the long-term strategy. You can already provision Kyma from Service Marketplace in BTP cockpit.

**Comment by PK85** [comment]
Final meetings with CIS team (Zahi)

Hi, we should talk about three things.

1) Add user_id (clientid from Cloud Management Service binding) to the [context](https://github.com/openservicebrokerapi/servicebroker/blob/v2.17/spec.md#body-8) in create binding request (PUT).

2) Set accepts_incomplete to false, because we've decided to use synchronous responses.

3) When binding expires we are removing entry form KEB database. Let's say user created 20 bindings and they all expired. In this case there will be no entries in KEB database, but get all bindings endpoint will return 20 binding with status OK. When user will try to get Credentials for one of them he will receive an error. Possible solution:
KEB will return expires_at field in [Binding Metadata](https://github.com/openservicebrokerapi/servicebroker/blob/v2.17/spec.md#binding-metadata-object) during binding creation. You can save this field in the database, and return only valid bindings to user.

**Comment by KsaweryZietara** [comment]
There are two ways of getting an access token for SAP Provisioning Service API:

- Using Password grant type
```
curl -L -X POST '<uaa_url>/oauth/token' \ 
-H 'Content-Type: application/x-www-form-urlencoded' \ 
-u '<clientid>:<clientsecret>' \ 
-d 'grant_type=password' \ 
-d 'username=<user email>' \
-d 'password=<password>'
```
During binding creation KEB receives body with context:
```
context: {
   "email":"email",
   "origin":"origin"
}
```
Context should be saved to database as `created_by = email + origin`.

**Comment by PK85** [comment]
Major decisions about implementation details: https://github.com/kyma-project/kyma-environment-broker/issues/1198#issuecomment-2404880767

**Comment by szwedm** [comment]
**Meeting notes 16.10.24**
- Service Binding states are not required, we can delete objects by determining `expires_at` and `kubeconfig` fields. If `expires_at` is older than current time SB should be deleted,
- `kubeconfig` value determines SB state. If it's empty, SB is in an unknown state, it may be `in progress` (800 ms max) or `error`,
- the first step in SB provisioning is creating a record in DB with empty `kubeconfig` which is populated in the last step,
- the first step in SB deprovisioning is the cleanup of resources (ServiceAccount, ClusterRole, ClusterRoleBinding) in SKR, the last step is SB removal from DB.

**Comment by PK85** [comment]
10.10.2024 - Summary from the meeting about using only token requests from SA from SKR and idempotent behaviour: https://github.com/kyma-project/kyma-environment-broker/issues/1198#issuecomment-2404880767

**Comment by ralikio** [comment]
10.10.2024 - Summary from the meeting about using only token requests from SA from SKR and idempotent behaviour:

Legend:
**BindingID**: means: BindingId - InstanceID pair on KEB side

**Contract between Provisioning Service and KEB bindings:**
- [ ] 1) KEB bindings returns 201 or 200 if everything ok, then Provisioning Service persist binding on their side
- [ ] 2) KEB bindings returns 400, 409, 500 if something wrong happen and then Provisioning Service DO NOT persist binding on their side, just pass error to the user

**KEB bindings responses details:** @MarekMichali 
- [x] 1) we return 201 when BindingID was not existing, and was created with success
- [ ] 2) we return 200 when BindingID WAS already existing, input parameters are the same and was created with success (in_progress,error is not success)
- [ ] 3) we return 400 when invalid input params provided  [JP - question - including not existent InstanceID?]
- [ ] 4) we return 409 when BindingID already exists but input params different
- [ ] 5) we return 500 if KEB itself is not able to finalize binding creation
- [x] 6) we return 200 on DELETE when bindings exists, [JP - question - 410 when does not exists?  - it seems that DELETE is not supposed to be idempotent] [MM - OSB says 410 if not exists]

**KEB implementation about handling binding related resources, like ServiceAccount, ClusterRole, ClusterRoleBidning**
- [x] 1) ~we need to have internal binding state representing ok, in_progress and error states~ - `The state is represented by kubeconfig field - non-empty kubeconfig: binding created ok; empty kubeconfig: otherwise`
- [ ] 2) probably we have two calls to db, ~~at the begining setting in_progress state and later at the end ok or error~~ at the beginning with an empty kubeconfig, and setting the kubeconfig when all is done/created without error
- [ ] 3) to eliminate temporary issues when calling SKR to create SA, CR, CRB we need to add retries (2,3 attempts) every 1,2 seconds  [JP - it seems that during Wednesday meeting we decided otherwise]
- [ ] 4) for whole binding creation we have internal overall timeout set to 15 seconds
- [ ] 5) If we have expired bindings we do not return them when GetBinding is comming from Provisioner Service. We just keep that binding internally to be cleaned up by binding-cleanup-job later.
- [x] 6) we have limit up to 10 valid bindings (expired ones do not count)
- [ ] 7) delete Bindings enpoint deletes all sub resources, if some of them already not exist go to next one and send success code
- [ ] 8) if get binding is called for ID that is expired or error we return not found status code

**KEB binding-cleanup-job details**
- [ ] 1) responsible to remove expired bindings (we call deletion binding endpoint with some infromation probbaly in header that our job call it, see other jobs how it is implemented. Delete binding endpoint must log it)
- [ ] 2) responsible and binding in error state (we call deletion binding endpoint with some infromation probbaly in header that our job call it, see other jobs how it is implemented. Delete binding endpoint must log it)
- [ ] 3) we call job once per day with nice log how many and what type of deletions happen (expired, errors, total)

**Comment by kwiatekus** [comment]
@PK85 
Is it planned to support creation of  kyma environment bindings via
 - btp cli
 - [sap btp terraform provider](https://registry.terraform.io/providers/SAP/btp/latest/docs/resources/subaccount_service_binding) ?

**Comment by PK85** [comment]
@kwiatekus 
BTP CLI and Cockpit was removed from the scope by CIS team. Maybe in the future we can back to them asking about that.

**Comment by IwonaLanger** [comment]
[Managing Kyma Runtime Using the Provisioning API of the SAP Cloud Management Service](https://help.sap.com/docs/btp/sap-business-technology-platform-internal/managing-kyma-runtime-using-provisioning-api-of-sap-cloud-management-service?&state=DRAFT&version=Internal) added and ready for review.
