### ISSUE TITLE
Extend Kyma Provisioning Parameters to allow multiple OIDC definitions

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma-environment-broker#423]
**Description**

Adjust set of [input parameters](https://github.com/kyma-project/kyma-environment-broker/blob/4ec8fc184786376a95b365d394dbd3b65b9a14ab/resources/keb/files/swagger.yaml#L2087)  of Kyma Service Instance Provisioning so that user can provide multiple OIDC configs (design `oidc` paramater so that in accepts a single config (for backwards compatibility) or an array).

Extend the [OIDC](https://github.com/kyma-project/kyma-environment-broker/blob/4ec8fc184786376a95b365d394dbd3b65b9a14ab/resources/keb/files/swagger.yaml#L2056) schema so that user could also define [requiedClaims](https://github.com/gardener/gardener-extension-shoot-oidc-service/blob/master/docs/usage/openidconnects.md?plain=1#L81C2-L81C86) (key-value pairs) that are essential for secure GH workflow access.

**AC**
Phase 1: migration - Size/M
 - [x] coordinate migration with SRE, see below
 - [x] Implement solutions for migration  (see: https://github.com/kyma-project/kyma/issues/18305#issuecomment-2612019987)

Phase 2: feature implementation - Size/L
 - [x] User can define multiple OIDC configs
 - [x] User can define required claims per OIDC config
 - [x] API proposal
   - [x] must be backward compatible
 - [x] Additional OIDC proposal Implementation (see: https://github.com/kyma-project/kyma/issues/18305#issuecomment-2128866460)
 - [x] Kubeconfig "context" enhancement to show all OIDCs that user sets. Default set to array[0]
https://github.com/kyma-project/kyma-environment-broker/pull/1936
    - [x] INFO: Busola will make use of that to allow user to select on of them.  Busola ticket: https://github.com/kyma-project/busola/issues/3653
 - [x] E2E test 
 - [x] Test load_current_config feature with OIDC data with object vs array. Check is existing values are available to user in the BTP form.
 - [x] Deploy: (only possible if Phase 1 fininshed)
   - [x] KIM ticket closed and deployed to all envs: https://github.com/kyma-project/infrastructure-manager/issues/803
   - [x] dev + ERS update
   - [x] stage + ERS update
   - [x] prod + ERS update 

 
**Reasons**

It is required to configure access to freshly created clusters via additional "workflow" OIDC
https://github.com/kyma-project/kyma/issues/18305

**Attachments**
 - [diagram](https://github.com/kyma-project/kyma/issues/18305#issuecomment-2128866460)
 - [flow diagram](https://github.com/kyma-project/kyma/issues/18519#issuecomment-1918966750)
 - https://community.sap.com/t5/additional-blogs-by-sap/using-github-actions-openid-connect-in-kubernetes/ba-p/13542513

Progress:
- we planned to start 12.022025, but some findings popup: 1) we should not have access to all SKRs, customer should grant that to use, and 2) many issuers support. We will discuss that 10.02.2025

Blockers:
- https://github.com/kyma-project/infrastructure-manager/issues/803
- NGPBUG-434545, UPDATE: 9.07 staging, 16.06 canary, 23.07 prod

**Comment by PK85** [comment]
Looks that Provisioner exposes APIs with pods and services CIDRs. We need to test it.

**Comment by kwiatekus** [comment]
As a first step we could enable that only for DEV landscape on a dedicated plan (`preview`):
 - make sure KEB on DEV is creating RuntimeCR 
 - make sure KEB can consume extended provisiong parameters (incl. required claims and multiple oidc)

**Comment by ralikio** [comment]
Proposed based on 

To preserve backward compatibility we would like to define a new parameter (e.g. "Additional OIDC") defined in the schema as a list. Old parameter will be functional and extended with requiredClaims. If user defined additional OIDC in the list and at the same time provides backward compatible one then we want to merge both.

**Comment by PK85** [comment]
blocked by KIM. Kim must be released on prod first

**Comment by PK85** [comment]
See what we need to do taking into account the migration:
- https://github.com/kyma-project/kyma/issues/18305#issuecomment-2612019987

**Comment by PK85** [comment]
Here Information what KEB must support, https://github.com/kyma-project/kyma/issues/18305#issuecomment-2128866460

Design API and present to me. We need to keep backward compatibility. That means our current oidc attribute could be a single object or array.

**Comment by MarekMichali** [comment]
We would like to provide the user with only the OIDC array list schema in the cockpit, but we still need to accept the OIDC object type for backward compatibility.
- [ ] check with btp cli if it is possible to send an object if it is not defined in the schema

Check if the schema supports loading the default OIDC as the first element of the array so that the default is defined explicitly. Below scenarios should be supported:
1. Create a new SKR without a user-defined OIDC. Only the default OIDC should be defined as the first element of the array
2. Create a new SKR with a default OIDC and a user-defined OIDC.
3. Create a new SKR without a default OIDC, only with a user-defined OIDC

The update schema should also only list additionalOIDC array list.
The GET function should return only the array list, even if only an object was originally provided

**Comment by MarekMichali** [comment]
For the `requiredClaims` value in the cockpit, we decided to use an array in which the user can define several key=value pairs. 
The decision to select `=` as a separator was based on [this](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#:~:text=A%20key%3Dvalue%20pair%20that%20describes%20a%20required%20claim%20in%20the%20ID%20Token.%20If%20set%2C%20the%20claim%20is%20verified%20to%20be%20present%20in%20the%20ID%20Token%20with%20a%20matching%20value.%20Repeat%20this%20flag%20to%20specify%20multiple%20claims).
<img width="250" alt="Image" src="https://github.com/user-attachments/assets/7784d8c7-d386-49ea-987c-4bb42b9615c6" />

JSON:
<img width="206" alt="Image" src="https://github.com/user-attachments/assets/78f36667-0a4a-4f4b-aba3-e23b1ebd54ca" />

**Comment by MarekMichali** [comment]
KEB must support provisioning and updating, where the OIDC property can be either an object or a list.

For provisioning 
| User Input Type                             | RuntimeCR additionalOIDC Population                            |
|---------------------------------------------|----------------------------------------------------------------|
| OIDC object sent                            | `additionalOIDC[0]` populated                                  |
| OIDC list with *n* elements                 | `additionalOIDC[0]` to `additionalOIDC[n-1]` populated        |
| Empty OIDC list with 0 elements             | `additionalOIDC` is an empty array                             |

For updating

**Comment by PK85** [comment]
Busola ticket added: https://github.com/kyma-project/busola/issues/3653

**Comment by MarekMichali** [comment]
Blocked by KIM ticket: https://github.com/kyma-project/infrastructure-manager/issues/803

**Comment by kwiatekus** [comment]
I tested this on DEV and it worked for me.
Here is my scenario:

I created a cluster on DEV with 
```json
{
...
"oidc": {
    "list": [
      {...},
      {
            "clientID": "kk-gh-token-test",
            "groupsClaim": "groups",
            "groupsPrefix": "-",
            "issuerURL": "https://token.actions.githubusercontent.com",
            "signingAlgs": [
                "RS256"
            ],
            "usernameClaim": "sub",
            "usernamePrefix": "actions-oidc:",
            "requiredClaims": [
                "repository=kwiatekus/kyma-demo",
                "ref=refs/heads/main"
            ]
       }
}
...
```
and configured a `clusterrolebinding` for github actions:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: User
    name: actions-oidc:repo:kwiatekus/kyma-demo:ref:refs/heads/main
    apiGroup: rbac.authorization.k8s.io
```

This allows me to run gh action to use the kyma instance.
I configured `APISERVER_URL` and `API_SERVER_CA` as repo secrets and the worflow is able to access the cluster using token from github:

https://github.com/kwiatekus/kyma-demo/blob/main/.github/workflows/test.yaml

**Comment by PK85** [comment]
blocked by: https://github.com/kyma-project/infrastructure-manager/issues/803

**Comment by PK85** [comment]
We checked if this is still blocked. Yes it is, nothing changed.
