### ISSUE TITLE
Kyma Environment Broker integration with Infrastructure Manager

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#58]
**Description**

In order to provide support for dynamic kubeconfigs in the Control Plane, KEB must integrate with the Cluster Inventory. 

**Reasons**

In the current architecture, KEB takes kubeconfig from the Provisioner, and creates a secret. The kubeconfig returned by the Provisioner is static, and should be no longer used by other components. Cluster Inventory is a new component that is responsible for dynamic kubeconfig management. KEB must delegate the task of kubeconfig secret creation to the Cluster Inventory by creating cluster CR.

**High-Level Diagram**

![Image](https://user-images.githubusercontent.com/9609118/269400983-1da67e69-1d31-4e68-ad0b-f3e062cc1f52.png)

**Acceptance criteria**
- [ ] 1) KEB must create Cluster CR containing the following data:
  - shoot name
  - secret name
- [ ] 2) Cluster CR must contain the same set of labels as defined [here](https://github.com/kyma-project/control-plane/blob/aa836f723a31c05c3d7ce663106c87425fdebf3c/components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go#L14)
- [ ] 3) Cluster CR name contains `RuntimeID`
- [ ] 4) The functionality in KEB is enabled by a feature flag
- [ ] 5) Decide how to pass responsibility for secret management to the infrastructure manager.
- [ ] 6) Check if KEB jobs require adjustments
- [ ] 7) Activate feature on dev and check if e2e are green 
- [ ] 8) KEB generates `RuntimeID`, instead of using the one generated by the Provisioner (we need to double check that if this is needed now. Maybe we should start to generate runtimeID when provisioned will be gone) 

**Info**

- The exact structure of the CR will be defined in this issue: https://github.com/kyma-project/infrastructure-manager/issues/9 .
- Provisioner will keep functionality by getting kubeconfig via  `getRuntimeStatus`

**Comment by piotrmiskiewicz** [comment]
# Runtime ID generation - how to move the ID generation to KEB, steps
1. Add a new field in the InstanceDetails - compass runtime Id (important: declare it as a pointer)
2. Add a method, which provides compass runtime Id. If the value (the new field) is `nil` - return runtimeId
3. Add proper label to kyma resource using the new method. If the runtime was not registered - then tha label must not be present
4. Gather new field in the Provisioner response which contains compass runtime Id. If Provisioner does not register runtime in the compass - we must store empty value.
5. At the end of the process, when provisioner is not called by KEB - runtimeID is generated and compass runtime Id is set to empty. If the label on Kyma resource is not needed - remove the labeling and compass runtime Id field/method

**Comment by piotrmiskiewicz** [comment]
Technical details:
1. KEB Generates runtimeID (should we do it now?):
 - generates runtime id in the initialisation step
 - new field for provisioner Runtime ID (and a helper method which returns this ID taking a value from one of those two fields)
2. A new step which creates a Cluster CR with provided shoot name and other important fields:
 - example of the CR: https://github.com/kyma-project/infrastructure-manager/blob/main/config/samples/infrastructuremanager_v1_gardenercluster.yaml
 - the step is enabled with a feature flag, by default, the step is disabled
 - the step is executed after the provisioner interaction, then wait for expected status (next step), those steps should be reused in the upgrade_cluster/update process (after a batch upgrade cluster all SKRs will have corresponding Cluster CR)
 - the deprovisioning process removes the CR  - new step, this is not guarded by feature flag!

**Comment by piotrmiskiewicz** [comment]
Tasks:
1. Update dependency to provisioner (go.mod) and implement a step which creates a CR with proper labels and spec
2. Implement a step, which checks an expected state
3. Add those steps to the provisioning process, add a test in cmd/broker for it (assertion for GardenerCluster, simulate infrastructure manager), add a feature flag which is disabled by default
4. Implement and add deprovisioning steps (remove cluster CR and wait for it). This step must be run before deleteKubeconfig. Finally deleteKubeconfig can be removed.
5. syncKubeconfig must not update the secret just create if needed
6. All getting kubeconfig steps must rely on the secret except

**Comment by ralikio** [comment]
Done
