### ISSUE TITLE
KEB release pipeline and Semantic Versioninig

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#98]
**Description**

We must provide a GA pipeline to release a new KEB version on the given tag. Then we can use it and bump in the resources directory.

**Reason**

Better release process than now.

**AC**
- [x] 1) take all the work we spend to create a release pipeline in the BTP-Manager, like:
  - [x] 1.1)  release notes generation
  - [x] 1.2) KEB new labels bug/enha/feature + checking them on PR level (same as in the BTP Manager)
- [x] 2) document new release process 
- [x] 3) rethink what kind of tests we use. Right now it is only unit tests. Think about how to test it more in the integration way. Result must be a decision what are the next steps.

**Links**
- info what SRE is doing around KEB testing: https://github.tools.sap/kyma/management-plane-charts/issues/354

**Comment by piotrmiskiewicz** [comment]
- test-infra release job: https://github.com/kyma-project/test-infra/pull/9265 (only KEB)
-

**Comment by MarekMichali** [comment]
- [ ] New release label validator
